server:
  port: 10000

spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/gulimall_pms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  jackson:
    date-format: yyyy-MM-dd HH-mm:ss
#  关闭缓存，调试时可以实时查看效果
  thymeleaf:
    cache: true

  redis:
    host: 192.168.33.10
    port: 6379
  cache:
    type: redis # 使用redis作为缓存
    redis:
#      time-to-live: 3600 # 过期时间
#      key-prefix: CACHE_ # 会导致自己在@Cacheable里设置的名字失效，所以这里不指定
      use-key-prefix: true # key值加前缀
      cache-null-values: true # 缓存控制

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

logging:
  level:
    root: INFO
    com.example.gulimall.product: debug
#    org.springframework.security: DEBUG